### ISSUE TITLE
[FEATURE] Add dark mode 

### ISSUE THREAD

**Issue by tarun42** [The-Robotics-Forum/netra#49]
**Describe the feature you want**
Add dark mode to application

**What is the current status of the feature?**
Completely new feature

**Comment by Vinamrata1086** [comment]
Can I work on this? (JWOC)

**Comment by avivijay19** [comment]
hello @Vinamrata1086 ,
Yes you can work on the issue but before assigning could you pls tell me the approach to solve that...!!

And what is your plan..??

**Comment by Vinamrata1086** [comment]
I will add the night mode switch button.
I have done a demo.

<img src="https://user-images.githubusercontent.com/59366156/105741649-95d20400-5f60-11eb-8268-479a297ea3b0.png" width=50%> 
<img src="https://user-images.githubusercontent.com/59366156/105741666-98ccf480-5f60-11eb-9135-134d25939289.png" width=50%>
<img src="https://user-images.githubusercontent.com/59366156/105741847-c9ad2980-5f60-11eb-8c52-a69c8aefa4fb.png" width=50%>

**Comment by avivijay19** [comment]
@Vinamrata1086,
could you create the switch button on action bar??

**Comment by Vinamrata1086** [comment]
> @Vinamrata1086,
> could you create the switch button on action bar??

Yes

**Comment by avivijay19** [comment]
Pls start working
